-- MyTour PostgreSQL initialization script.
-- Intended for a fresh database. When using this script with Spring Boot/JPA,
-- prefer validating the schema from Hibernate instead of letting Hibernate own it.

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    username_normalized VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uq_app_users_username_normalized UNIQUE (username_normalized),
    CONSTRAINT chk_app_users_username_length CHECK (char_length(btrim(username)) BETWEEN 3 AND 50),
    CONSTRAINT chk_app_users_username_normalized_matches CHECK (username_normalized = lower(btrim(username))),
    CONSTRAINT chk_app_users_password_hash_not_blank CHECK (btrim(password_hash) <> '')
);

CREATE TABLE IF NOT EXISTS tours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    start_location VARCHAR(255) NOT NULL,
    end_location VARCHAR(255) NOT NULL,
    transport_type VARCHAR(20) NOT NULL,
    timezone_id VARCHAR(64) NOT NULL DEFAULT 'UTC',
    planned_distance_m NUMERIC(12, 2) NOT NULL DEFAULT 0,
    estimated_duration_s INTEGER NOT NULL DEFAULT 0,
    cover_image_path VARCHAR(1024),
    cover_image_original_filename VARCHAR(255),
    cover_image_content_type VARCHAR(100),
    cover_image_size_bytes BIGINT,
    log_count INTEGER NOT NULL DEFAULT 0,
    popularity_score INTEGER NOT NULL DEFAULT 0,
    popularity_category VARCHAR(40) NOT NULL DEFAULT 'NEW',
    popularity_label VARCHAR(80) NOT NULL DEFAULT 'new',
    child_friendliness_score INTEGER NOT NULL DEFAULT 0,
    child_friendliness_category VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    child_friendliness_label VARCHAR(80) NOT NULL DEFAULT 'unknown',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_tours_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE,
    CONSTRAINT chk_tours_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_tours_start_location_not_blank CHECK (btrim(start_location) <> ''),
    CONSTRAINT chk_tours_end_location_not_blank CHECK (btrim(end_location) <> ''),
    CONSTRAINT chk_tours_transport_type CHECK (transport_type IN ('BIKE', 'HIKE', 'RUNNING', 'VACATION')),
    CONSTRAINT chk_tours_timezone_not_blank CHECK (btrim(timezone_id) <> ''),
    CONSTRAINT chk_tours_planned_distance_non_negative CHECK (planned_distance_m >= 0),
    CONSTRAINT chk_tours_estimated_duration_non_negative CHECK (estimated_duration_s >= 0),
    CONSTRAINT chk_tours_cover_image_size_non_negative CHECK (cover_image_size_bytes IS NULL OR cover_image_size_bytes >= 0),
    CONSTRAINT chk_tours_log_count_non_negative CHECK (log_count >= 0),
    CONSTRAINT chk_tours_popularity_score_non_negative CHECK (popularity_score >= 0),
    CONSTRAINT chk_tours_popularity_category CHECK (popularity_category IN ('NEW', 'RARELY_USED', 'POPULAR', 'VERY_POPULAR')),
    CONSTRAINT chk_tours_popularity_label_not_blank CHECK (btrim(popularity_label) <> ''),
    CONSTRAINT chk_tours_child_friendliness_score_range CHECK (child_friendliness_score BETWEEN 0 AND 100),
    CONSTRAINT chk_tours_child_friendliness_category CHECK (
        child_friendliness_category IN (
            'UNKNOWN',
            'FAMILY_FRIENDLY',
            'MODERATE_FAMILY_SUITABILITY',
            'CHALLENGING_ROUTE',
            'ADULT_ORIENTED'
        )
    ),
    CONSTRAINT chk_tours_child_friendliness_label_not_blank CHECK (btrim(child_friendliness_label) <> '')
);

CREATE TABLE IF NOT EXISTS tour_routes (
    tour_id BIGINT PRIMARY KEY,
    route_source VARCHAR(50) NOT NULL DEFAULT 'OPENROUTESERVICE',
    route_profile VARCHAR(50) NOT NULL,
    start_lat NUMERIC(9, 6) NOT NULL,
    start_lon NUMERIC(9, 6) NOT NULL,
    end_lat NUMERIC(9, 6) NOT NULL,
    end_lon NUMERIC(9, 6) NOT NULL,
    midpoint_lat NUMERIC(9, 6) NOT NULL,
    midpoint_lon NUMERIC(9, 6) NOT NULL,
    route_geometry JSONB NOT NULL,
    route_fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tour_routes_tour FOREIGN KEY (tour_id) REFERENCES tours (id) ON DELETE CASCADE,
    CONSTRAINT chk_tour_routes_source_not_blank CHECK (btrim(route_source) <> ''),
    CONSTRAINT chk_tour_routes_profile_not_blank CHECK (btrim(route_profile) <> ''),
    CONSTRAINT chk_tour_routes_start_lat_range CHECK (start_lat BETWEEN -90 AND 90),
    CONSTRAINT chk_tour_routes_end_lat_range CHECK (end_lat BETWEEN -90 AND 90),
    CONSTRAINT chk_tour_routes_midpoint_lat_range CHECK (midpoint_lat BETWEEN -90 AND 90),
    CONSTRAINT chk_tour_routes_start_lon_range CHECK (start_lon BETWEEN -180 AND 180),
    CONSTRAINT chk_tour_routes_end_lon_range CHECK (end_lon BETWEEN -180 AND 180),
    CONSTRAINT chk_tour_routes_midpoint_lon_range CHECK (midpoint_lon BETWEEN -180 AND 180),
    CONSTRAINT chk_tour_routes_geometry_object CHECK (jsonb_typeof(route_geometry) = 'object')
);

CREATE TABLE IF NOT EXISTS tour_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL,
    performed_at TIMESTAMPTZ NOT NULL,
    comment TEXT,
    difficulty SMALLINT NOT NULL,
    total_distance_m NUMERIC(12, 2) NOT NULL,
    total_time_s INTEGER NOT NULL,
    rating SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_tour_logs_tour FOREIGN KEY (tour_id) REFERENCES tours (id) ON DELETE CASCADE,
    CONSTRAINT chk_tour_logs_difficulty_range CHECK (difficulty BETWEEN 1 AND 5),
    CONSTRAINT chk_tour_logs_total_distance_non_negative CHECK (total_distance_m >= 0),
    CONSTRAINT chk_tour_logs_total_time_positive CHECK (total_time_s > 0),
    CONSTRAINT chk_tour_logs_rating_range CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS tour_log_weather (
    tour_log_id BIGINT PRIMARY KEY,
    provider VARCHAR(50) NOT NULL DEFAULT 'OPEN_METEO',
    provider_dataset VARCHAR(100),
    lookup_lat NUMERIC(9, 6) NOT NULL,
    lookup_lon NUMERIC(9, 6) NOT NULL,
    weather_observed_at TIMESTAMPTZ NOT NULL,
    temperature_c NUMERIC(5, 2),
    relative_humidity_percent NUMERIC(5, 2),
    precipitation_mm NUMERIC(8, 2),
    weather_code INTEGER,
    weather_description VARCHAR(120),
    wind_speed_kmh NUMERIC(6, 2),
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tour_log_weather_log FOREIGN KEY (tour_log_id) REFERENCES tour_logs (id) ON DELETE CASCADE,
    CONSTRAINT chk_tour_log_weather_provider_not_blank CHECK (btrim(provider) <> ''),
    CONSTRAINT chk_tour_log_weather_lookup_lat_range CHECK (lookup_lat BETWEEN -90 AND 90),
    CONSTRAINT chk_tour_log_weather_lookup_lon_range CHECK (lookup_lon BETWEEN -180 AND 180),
    CONSTRAINT chk_tour_log_weather_humidity_range CHECK (
        relative_humidity_percent IS NULL OR relative_humidity_percent BETWEEN 0 AND 100
    ),
    CONSTRAINT chk_tour_log_weather_precipitation_non_negative CHECK (
        precipitation_mm IS NULL OR precipitation_mm >= 0
    ),
    CONSTRAINT chk_tour_log_weather_wind_speed_non_negative CHECK (
        wind_speed_kmh IS NULL OR wind_speed_kmh >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_tours_user_id ON tours (user_id);
CREATE INDEX IF NOT EXISTS idx_tours_user_transport_type ON tours (user_id, transport_type);
CREATE INDEX IF NOT EXISTS idx_tours_user_popularity ON tours (user_id, popularity_category);
CREATE INDEX IF NOT EXISTS idx_tours_user_child_friendliness ON tours (user_id, child_friendliness_category);

CREATE INDEX IF NOT EXISTS idx_tour_logs_tour_id ON tour_logs (tour_id);
CREATE INDEX IF NOT EXISTS idx_tour_logs_tour_performed_at ON tour_logs (tour_id, performed_at DESC);

CREATE INDEX IF NOT EXISTS idx_tour_log_weather_observed_at ON tour_log_weather (weather_observed_at);

CREATE INDEX IF NOT EXISTS idx_tours_full_text_search ON tours USING GIN (
    to_tsvector(
        'simple',
        coalesce(name, '') || ' ' ||
        coalesce(description, '') || ' ' ||
        coalesce(start_location, '') || ' ' ||
        coalesce(end_location, '') || ' ' ||
        coalesce(transport_type, '') || ' ' ||
        coalesce(popularity_label, '') || ' ' ||
        coalesce(child_friendliness_label, '')
    )
);

CREATE INDEX IF NOT EXISTS idx_tour_logs_full_text_search ON tour_logs USING GIN (
    to_tsvector(
        'simple',
        coalesce(comment, '') || ' difficulty ' || difficulty::text || ' rating ' || rating::text
    )
);

CREATE INDEX IF NOT EXISTS idx_tour_log_weather_full_text_search ON tour_log_weather USING GIN (
    to_tsvector(
        'simple',
        coalesce(provider_dataset, '') || ' ' ||
        coalesce(weather_description, '')
    )
);
